/*
 * Universidad Simón Bolívar.
 * Departamento de Computación y Tecnología de la Información.
 * Asignatura: Laboratorio de Bases de Datos I.
 * Estudiantes:
 * 		Br. Fernando Pérez, carné: 12-11152.
 *		Br. Leslie Rodrigues, carné: 10-10613.
 *
 * Archivo: createTables.sql
 * Descripción: script de sql para crear las tablas en la base de datos, con sus
 * respectivos atributos. En este archivo no se incluyen los constraints.
 * Última modificación: 22-05-2015.
 */

CREATE TABLE ADMINISTRATIVO(
	A_CEDULA VARCHAR(9),
	A_SUELDO_BASE NUMERIC(6,2)
);

CREATE TABLE BONO_SABATINO(
	B_MONTO NUMERIC(4,2)
);

CREATE TABLE CARGO(
	CAR_SUELDO_BASE NUMERIC(6,2),
	CAR_CARGO VARCHAR(13)
);

CREATE TABLE CAMBIO(
	CAM_RECIBO NUMERIC(7,0),	
	CAM_CLIENTE VARCHAR(9),
	CAM_EJEMPLAR_CLIENTE VARCHAR(50),
	CAM_EJEMPLAR_TIENDA VARCHAR(50),
	CAM_VENDEDOR VARCHAR(9)
);

CREATE TABLE CATEGORIA(
	CAT_SUELDO_BASE NUMERIC(6,2),
	CAT_CARGO VARCHAR(3)
);

CREATE TABLE CLIENTE(
	CL_CEDULA VARCHAR(9),
	CL_NOMBRE_COMPLETO VARCHAR(35),
	CL_DIRECCION VARCHAR(50),
	CL_TELEFONO NUMERIC(11,0),
	CL_CORREO_ELECTRONICO VARCHAR(254)
);

CREATE TABLE COMPRA(
	COM_NRO_FACTURA NUMERIC(7,0),
	COM_RIF_TIENDA VARCHAR(12),
	COM_CLIENTE VARCHAR(9),
	COM_EJEMPLAR VARCHAR(50),
	COM_VENDEDOR VARCHAR(9)
);

CREATE TABLE DEPENDIENTE(
	D_NUMERO_DEPENDIENTE NUMERIC(3,0),
	D_ASEGURADO BOOLEAN,
	D_CEDULA VARCHAR(9),
	D_EDAD NUMERIC(2,0),
	D_NOMBRE_COMPLETO VARCHAR(35),
	D_PRIMA NUMERIC(7,0),
	D_SEXO VARCHAR(9)
);

CREATE TABLE EJEMPLAR(
	E_NUMERO_INVENTARIO NUMERIC(5,0)
);

CREATE TABLE EJEMPLAR_NUEVO(
	E_N_NUMERO_INVENTARIO NUMERIC(5,0),
	E_N_INFORMACION_PRODUCTO VARCHAR(50)
);

CREATE TABLE EJEMPLAR_USADO(
	E_U_NUMERO_INVENTARIO NUMERIC(5,0),
	E_U_INFORMACION_PRODUCTO VARCHAR(50)
);

CREATE TABLE EMPLEADO(
	EM_CEDULA VARCHAR(9),
	EM_CORREO_ELECTRONICO VARCHAR(254),
	EM_DIRECCION VARCHAR(50),
	EM_FECHA_DE_INGRESO TIMESTAMP,
	EM_NOMBRE_COMPLETO VARCHAR(35)
	
);

CREATE TABLE ENTREGA(
	EN_PROVEEDOR VARCHAR(12),
	EN_PRODUCTO_NUEVO NUMERIC(50,0),
	EN_FACTURA NUMERIC(7,0),
	EN_RIF_PROVEEDORA VARCHAR(12)
);

CREATE TABLE ES_FAMILIAR(
	ES_F_EMPLEADO VARCHAR(9),
	ES_F_DEPENDIENTE NUMERIC(3,0),
	ES_F_PARENTESCO VARCHAR(7)
);

CREATE TABLE FACTURA(
	F_NUMERO_FACTURA NUMERIC(7,0),
	F_RIF_EMPRESA VARCHAR(12),
	F_CLAVE_TRANSACCION NUMERIC(10,0),
	F_METODO_DE_PAGO VARCHAR(22),
	F_MONTO NUMERIC(9,2),
	F_NUMERO_CUENTA_TRANSACCION NUMERIC(18,0)
);


CREATE TABLE LISTA_DE_PRECIOS(
	L_P_PRECIO NUMERIC(7),
	L_P_ANIO_DE_ELABORACION NUMERIC (4,0),
	L_P_MARCA VARCHAR(20),
	L_P_MODELO VARCHAR(20)
);

CREATE TABLE NUEVO(
	N_NUMERO_ORDEN NUMERIC(5,0),
	N_CANTIDAD_EXISTENTE NUMERIC(4,0),
	N_NIVEL_MINIMO NUMERIC(3,0)
);

CREATE TABLE ORDEN(
	O_NUMERO NUMERIC(7,0),
	O_FECHA TIMESTAMP,
	O_MONTO_TOTAL NUMERIC(8,0),
	O_PROVEEDOR VARCHAR(12)
);

CREATE TABLE PIDE(
	PI_NRO_PEDIDO NUMERIC(7,0),
	PI_PRODUCTO NUMERIC(5,0),
	PI_CLIENTE VARCHAR(9),
	PI_ES_NUEVO BOOLEAN
);

CREATE TABLE PRIMA(
	PRI_MONTO NUMERIC(7,0),
	PRI_GENERO VARCHAR(9),
	PRI_RANGO_ETARIO VARCHAR(7)
);

CREATE TABLE PRODUCTO(
	PROD_IDENTIFICADOR NUMERIC(5,0),
	PROD_ANIO_ELABORACION NUMERIC(4,0),
	PROD_CATEGORIA VARCHAR(20),
	PROD_COSTO NUMERIC(7,2),
	PROD_MARCA VARCHAR(20),
	PROD_MODELO VARCHAR(20)
);

CREATE TABLE PROVEEDOR(
	PROV_RIF VARCHAR(12)
);

CREATE TABLE RECIBO(
	R_NUMERO_RECIBO NUMERIC(7,0),
	R_CLAVE_TRANSACCION NUMERIC(10,0),
	R_METODO_DE_PAGO VARCHAR(22),
	R_MONTO NUMERIC(9,2),
	R_NUMERO_CUENTA_TRANSACCION NUMERIC(18,0),
	R_RIF_EMPRESA VARCHAR(12)
);

CREATE TABLE SE_INCLUYE(
	S_I_ORDEN NUMERIC(7,0),
	S_I_PRODUCTO NUMERIC(5,0),
	S_I_CANTIDAD NUMERIC(3,0),
	S_I_CODIGO_PRODUCTO NUMERIC(5,0),
	S_I_DESCRIPCION VARCHAR(50),
	S_I_PRECIO_UNITARIO NUMERIC(7,2)
);

CREATE TABLE TELEFONO_EMPLEADO(
	T_E_CEDULA	VARCHAR(9),
	T_E_NUMERO	NUMERIC(11,0)
);

CREATE TABLE USADO(
	U_IDENTIFICADOR NUMERIC(5,0)
);

CREATE TABLE VENDEDOR(
	VEN_CEDULA VARCHAR(9),
	VEN_COMISION NUMERIC(6,2),
	VEN_NRO_SABADOS NUMERIC(1,0),
	VEN_REMUNERACION NUMERIC(6,2),
	VEN_SUELDO_BASE NUMERIC(6,2),
	VEN_TURNO VARCHAR(7)
);

CREATE TABLE VENTA(
	V_RECIBO NUMERIC(7,0),
	V_CLIENTE VARCHAR(9),
	V_EJEMPLAR_USADO_VENTA VARCHAR(50),
	V_PRECIO_DE_VENTA NUMERIC(7,2),
	V_VENDEDOR VARCHAR(9)
);



/*

CREATE TABLE VEHICULO_ROBADO(
V_PLACA		CHAR(7) CONSTRAINT PK_VEHICULO_ROBADO PRIMARY KEY,
V_MARCA  	VARCHAR(10) CONSTRAINT DOM_VEH_ROBADO_V_MARCA CHECK 
			     (V_MARCA IN ('FORD','CHEVROLET','VOLKSWAGEN','MAZDA','RENAULT','HONDA',
			     	          'TOYOTA','NISSAN','MERCEDES','AUDI','PORSCHE','SUSUKI',
					  'CADILLAC','CITROEN','CHRYSLER','BMW','DODGE','SEAT',
					  'PEUGOT','LAND ROVER','FIAT','MASERATI','LEXUS','MITSUBISHI',
					  'HYUNDAI','DAEWOO','ALFA ROMEO', 'JEEP')),
V_MODELO 	VARCHAR(10) CONSTRAINT DOM_VEH_ROBADO_V_MODELO CHECK
			     (V_MODELO IN ('SEDAN', 'DEPORTIVO','PICKUP','FURGONETA','MICRO','CAMIONETA')),
V_ANIO  	NUMERIC(4,0) CONSTRAINT DOM_VEH_ROBADO_V_ANIO CHECK (V_ANIO>1800),
V_COLOR		VARCHAR(10) CONSTRAINT DOM_VEH_ROBADO_V_COLOR CHECK 
			    (V_COLOR IN ('BLANCO','NEGRO','PLATA','DORADO','GRIS','AZUL',
			    	         'ROJO','AMARILLO','VERDE','CAFE', 'NARANJA','VIOLETA')),
V_ID_UP	VARCHAR(14),
V_FECHA		TIMESTAMP,
CONSTRAINT FK_VEHICULO_ROBADO_DETENCION FOREIGN KEY (V_ID_UP,V_FECHA)
	   				REFERENCES DETENCION
);
CREATE TABLE DENUNCIA_ROBO(
DR_CI		VARCHAR(9), 
DR_FECHA	TIMESTAMP,
DR_NOMBRE 	VARCHAR(40),
DR_LUGAR_ROBO	VARCHAR(40),
DR_FECHA_ROBO	TIMESTAMP,
DR_PLACA	CHAR(7) CONSTRAINT FK_DENUNCIA_VEHICULO_ROBADO REFERENCES VEHICULO_ROBADO,
DR_ID_UP	VARCHAR(14) CONSTRAINT FK_DENUNCIA_ROBO_UNIDAD_PAT REFERENCES UNIDAD_PATRULLAJE,
CONSTRAINT PK_DENUNCIA_ROBO PRIMARY KEY(DR_CI,DR_FECHA),
CONSTRAINT EXP_DENUNCIA_ROBO_R01 CHECK(DR_FECHA_ROBO<=DR_FECHA)
);

	
CREATE TABLE SOSPECHOSO(
S_CI		VARCHAR(9) CONSTRAINT PK_SOSPECHOSO PRIMARY KEY,
S_NOMBRE	VARCHAR(40),
S_NUMEXP		NUMERIC(7,0) CONSTRAINT AK_SOSPECHOSO UNIQUE
);

CREATE TABLE SE_DETIENE(
SD_CI		VARCHAR(9)CONSTRAINT FK_SE_DETIENE_SOSPECHOSO 
			   REFERENCES SOSPECHOSO,
SD_ID_UP	VARCHAR(14),
SD_FECHA	TIMESTAMP,
CONSTRAINT FK_SE_DETIENE_DETENCION FOREIGN KEY (SD_ID_UP, SD_FECHA)
	   REFERENCES DETENCION
);*/
