/*
 * Universidad Simón Bolívar.
 * Departamento de Computación y Tecnología de la Información.
 * Asignatura: Laboratorio de Bases de Datos I.
 * Estudiantes:
 * 		Br. Fernando Pérez, carné: 12-11152.
 *		Br. Leslie Rodrigues, carné: 10-10613.
 *
 * Archivo: dropTables.sql
 * Descripción: script de sql para eliminar las tablas de la base de datos.
 * Última modificación: 22-05-2015.
 */

DROP TABLE ADMINISTRATIVO;
DROP TABLE BONO_SABATINO;
DROP TABLE CARGO;
DROP TABLE CAMBIO;
DROP TABLE CATEGORIA;
DROP TABLE CLIENTE;
DROP TABLE COMPRA;
DROP TABLE DEPENDIENTE;
DROP TABLE EJEMPLAR;
DROP TABLE EJEMPLAR_NUEVO;
DROP TABLE EJEMPLAR_USADO;
DROP TABLE EMPLEADO;
DROP TABLE ENTREGA;
DROP TABLE ES_FAMILIAR;
DROP TABLE FACTURA;
DROP TABLE LISTA_DE_PRECIOS;
DROP TABLE NUEVO;
DROP TABLE ORDEN;
DROP TABLE PIDE;
DROP TABLE PRIMA;
DROP TABLE PRODUCTO;
DROP TABLE PROVEEDOR;
DROP TABLE RECIBO;
DROP TABLE SE_INCLUYE;
DROP TABLE TELEFONO_EMPLEADO;
DROP TABLE USADO;
DROP TABLE VENDEDOR;
DROP TABLE VENTA;
