DROP TABLE SE_DETIENE;
DROP TABLE SOSPECHOSO;
DROP TABLE DENUNCIA_ROBO;
DROP TABLE VEHICULO_ROBADO;
DROP TABLE DETENCION;
DROP TABLE UNIDAD_PATRULLAJE;


CREATE TABLE UNIDAD_PATRULLAJE(
U_ID_UP		VARCHAR(14) CONSTRAINT PK_UNIDAD_PATRULLAJE PRIMARY KEY,
U_ZONA		VARCHAR(40) 
);

CREATE TABLE DETENCION(
D_ID_UP	VARCHAR(14) CONSTRAINT FK_DETENCION_UNIDAD_PATRULLAJE 
			REFERENCES UNIDAD_PATRULLAJE,
D_FECHA	TIMESTAMP,
D_LUGAR 	VARCHAR(40) ,
CONSTRAINT PK_DETENCION PRIMARY KEY (D_ID_UP,D_FECHA));

CREATE TABLE VEHICULO_ROBADO(
V_PLACA		CHAR(7) CONSTRAINT PK_VEHICULO_ROBADO PRIMARY KEY,
V_MARCA  	VARCHAR(10) CONSTRAINT DOM_VEH_ROBADO_V_MARCA CHECK 
			     (V_MARCA IN ('FORD','CHEVROLET','VOLKSWAGEN','MAZDA','RENAULT','HONDA',
			     	          'TOYOTA','NISSAN','MERCEDES','AUDI','PORSCHE','SUSUKI',
					  'CADILLAC','CITROEN','CHRYSLER','BMW','DODGE','SEAT',
					  'PEUGOT','LAND ROVER','FIAT','MASERATI','LEXUS','MITSUBISHI',
					  'HYUNDAI','DAEWOO','ALFA ROMEO', 'JEEP')),
V_MODELO 	VARCHAR(10) CONSTRAINT DOM_VEH_ROBADO_V_MODELO CHECK
			     (V_MODELO IN ('SEDAN', 'DEPORTIVO','PICKUP','FURGONETA','MICRO','CAMIONETA')),
V_ANIO  	NUMERIC(4,0) CONSTRAINT DOM_VEH_ROBADO_V_ANIO CHECK (V_ANIO>1800),
V_COLOR		VARCHAR(10) CONSTRAINT DOM_VEH_ROBADO_V_COLOR CHECK 
			    (V_COLOR IN ('BLANCO','NEGRO','PLATA','DORADO','GRIS','AZUL',
			    	         'ROJO','AMARILLO','VERDE','CAFE', 'NARANJA','VIOLETA')),
V_ID_UP	VARCHAR(14),
V_FECHA		TIMESTAMP,
CONSTRAINT FK_VEHICULO_ROBADO_DETENCION FOREIGN KEY (V_ID_UP,V_FECHA)
	   				REFERENCES DETENCION
);
CREATE TABLE DENUNCIA_ROBO(
DR_CI		VARCHAR(9), 
DR_FECHA	TIMESTAMP,
DR_NOMBRE 	VARCHAR(40),
DR_LUGAR_ROBO	VARCHAR(40),
DR_FECHA_ROBO	TIMESTAMP,
DR_PLACA	CHAR(7) CONSTRAINT FK_DENUNCIA_VEHICULO_ROBADO REFERENCES VEHICULO_ROBADO,
DR_ID_UP	VARCHAR(14) CONSTRAINT FK_DENUNCIA_ROBO_UNIDAD_PAT REFERENCES UNIDAD_PATRULLAJE,
CONSTRAINT PK_DENUNCIA_ROBO PRIMARY KEY(DR_CI,DR_FECHA),
CONSTRAINT EXP_DENUNCIA_ROBO_R01 CHECK(DR_FECHA_ROBO<=DR_FECHA)
);

	
CREATE TABLE SOSPECHOSO(
S_CI		VARCHAR(9) CONSTRAINT PK_SOSPECHOSO PRIMARY KEY,
S_NOMBRE	VARCHAR(40),
S_NUMEXP		NUMERIC(7,0) CONSTRAINT AK_SOSPECHOSO UNIQUE
);

CREATE TABLE SE_DETIENE(
SD_CI		VARCHAR(9)CONSTRAINT FK_SE_DETIENE_SOSPECHOSO 
			   REFERENCES SOSPECHOSO,
SD_ID_UP	VARCHAR(14),
SD_FECHA	TIMESTAMP,
CONSTRAINT FK_SE_DETIENE_DETENCION FOREIGN KEY (SD_ID_UP, SD_FECHA)
	   REFERENCES DETENCION
);